# Generated by Django 4.2 on 2023-07-13 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userPosts',
            fields=[
                ('postID', models.IntegerField(primary_key=True, serialize=False)),
                ('postDate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
