# Generated by Django 4.2 on 2023-07-13 01:47

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
